version: "3"

services:
  odoo:
    build: ./odoo
    #image: cubit9/odoo13:${ODOO_VERSION}
    container_name: 'odoo'
    restart: 'always'
    ports:
      - "8069:8069"
      - "8071:8071"
    links:
      # pgsql is reachable from odoo at the hostnames pgsql and db
      - "pgsql:db"
    volumes: 
      - ${ODOO_DATA_SAVE_PATH}/data:/var/lib/odoo  # odoo filestore
      - ${ODOO_DATA_SAVE_PATH}/addons:/mnt/extra-addons
    networks:
      - frontend
      - backend

  pgsql:
    image: postgres:${POSTGRES_VERSION}
    container_name: 'pgsql'
    restart: 'always'
    volumes: 
      - ${POSTGRES_DATA_SAVE_PATH}/data:/var/lib/postgresql/data
      - ${POSTGRES_DATA_SAVE_PATH}/config:/etc/postgresql/${POSTGRES_VERSION}/main
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.1.0/24"

  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.25.2.0/24"
    internal: true